"""first migration

Revision ID: 60811572d9c7
Revises: 
Create Date: 2026-04-07 17:48:04.489205

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60811572d9c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=70), nullable=False),
    sa.Column('logo_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sa.Enum('PRIVATE', 'PUBLIC', 'CHARTER', name='schooltype'), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_name'), 'school', ['name'], unique=False)
    op.create_index('uq_school_name_active', 'school', ['name'], unique=True, sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.create_index('uq_school_phone_active', 'school', ['phone'], unique=True, sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('school_invite',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'TEACHER', name='inviterole'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_invite_code'), 'school_invite', ['code'], unique=False)
    op.create_index(op.f('ix_school_invite_school_id'), 'school_invite', ['school_id'], unique=False)
    op.create_index('uq_school_invite_code_active', 'school_invite', ['code'], unique=True, sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.create_index('uq_school_invite_school_role_active', 'school_invite', ['school_id', 'role'], unique=True, sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.create_table('school_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'TEACHER', name='schoolrole'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_user_school_id'), 'school_user', ['school_id'], unique=False)
    op.create_index(op.f('ix_school_user_user_id'), 'school_user', ['user_id'], unique=False)
    op.create_index('uq_school_user_role_active', 'school_user', ['user_id', 'school_id', 'role'], unique=True, sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_school_user_role_active', table_name='school_user', sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.drop_index(op.f('ix_school_user_user_id'), table_name='school_user')
    op.drop_index(op.f('ix_school_user_school_id'), table_name='school_user')
    op.drop_table('school_user')
    op.drop_index('uq_school_invite_school_role_active', table_name='school_invite', sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.drop_index('uq_school_invite_code_active', table_name='school_invite', sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.drop_index(op.f('ix_school_invite_school_id'), table_name='school_invite')
    op.drop_index(op.f('ix_school_invite_code'), table_name='school_invite')
    op.drop_table('school_invite')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index('uq_school_phone_active', table_name='school', sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.drop_index('uq_school_name_active', table_name='school', sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.drop_index(op.f('ix_school_name'), table_name='school')
    op.drop_table('school')
    # ### end Alembic commands ###
