"""add is_closed to evaluations

Revision ID: 6eeb18827394
Revises: 8fa4b48c510e
Create Date: 2026-05-07 16:52:06.568923

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eeb18827394'
down_revision: Union[str, Sequence[str], None] = '8fa4b48c510e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'evaluations',
        sa.Column('is_closed', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluations', 'is_closed')
    # ### end Alembic commands ###
