"""add term subject averages

Revision ID: 85ab8db9bec9
Revises: c003e8f199a2
Create Date: 2026-05-08 12:48:56.836295

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85ab8db9bec9'
down_revision: Union[str, Sequence[str], None] = 'c003e8f199a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('term_subject_averages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('saber_score', sa.Float(), nullable=False),
    sa.Column('hacer_score', sa.Float(), nullable=False),
    sa.Column('ser_score', sa.Float(), nullable=False),
    sa.Column('autoevaluacion_score', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_term_subject_averages_assignment_id'), 'term_subject_averages', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_term_subject_averages_school_id'), 'term_subject_averages', ['school_id'], unique=False)
    op.create_index(op.f('ix_term_subject_averages_student_id'), 'term_subject_averages', ['student_id'], unique=False)
    op.create_index(op.f('ix_term_subject_averages_term_id'), 'term_subject_averages', ['term_id'], unique=False)
    op.create_index('uq_term_subject_averages_assignment_term_student_active', 'term_subject_averages', ['assignment_id', 'term_id', 'student_id'], unique=True, sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_term_subject_averages_assignment_term_student_active', table_name='term_subject_averages', sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.drop_index(op.f('ix_term_subject_averages_term_id'), table_name='term_subject_averages')
    op.drop_index(op.f('ix_term_subject_averages_student_id'), table_name='term_subject_averages')
    op.drop_index(op.f('ix_term_subject_averages_school_id'), table_name='term_subject_averages')
    op.drop_index(op.f('ix_term_subject_averages_assignment_id'), table_name='term_subject_averages')
    op.drop_table('term_subject_averages')
    # ### end Alembic commands ###
