"""add attendance tables

Revision ID: c003e8f199a2
Revises: 6eeb18827394
Create Date: 2026-05-07 17:49:51.164167

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c003e8f199a2'
down_revision: Union[str, Sequence[str], None] = '6eeb18827394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_statuses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_statuses_name'), 'attendance_statuses', ['name'], unique=False)
    op.create_index('uq_attendance_statuses_name_active', 'attendance_statuses', ['name'], unique=True, sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.create_table('attendance_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_sessions_assignment_id'), 'attendance_sessions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_name'), 'attendance_sessions', ['name'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_school_id'), 'attendance_sessions', ['school_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_term_id'), 'attendance_sessions', ['term_id'], unique=False)
    op.create_index('uq_attendance_sessions_assignment_term_name_date_active', 'attendance_sessions', ['assignment_id', 'term_id', 'name', 'attendance_date'], unique=True, sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.create_table('attendance_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('status_id', sa.Uuid(), nullable=False),
    sa.Column('observation', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('attendance_session_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['attendance_session_id'], ['attendance_sessions.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['attendance_statuses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_records_attendance_session_id'), 'attendance_records', ['attendance_session_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_school_id'), 'attendance_records', ['school_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_status_id'), 'attendance_records', ['status_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_student_id'), 'attendance_records', ['student_id'], unique=False)
    op.create_index('uq_attendance_records_session_student_active', 'attendance_records', ['attendance_session_id', 'student_id'], unique=True, sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_attendance_records_session_student_active', table_name='attendance_records', sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.drop_index(op.f('ix_attendance_records_student_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_status_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_school_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_attendance_session_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index('uq_attendance_sessions_assignment_term_name_date_active', table_name='attendance_sessions', sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.drop_index(op.f('ix_attendance_sessions_term_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_school_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_name'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_assignment_id'), table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    op.drop_index('uq_attendance_statuses_name_active', table_name='attendance_statuses', sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.drop_index(op.f('ix_attendance_statuses_name'), table_name='attendance_statuses')
    op.drop_table('attendance_statuses')
    # ### end Alembic commands ###
