from .course_schema import (
    CourseCreate,
    CourseFormOptionsRead,
    CourseRead,
    CourseUpdate,
    PaginatedCourse,
    SchoolLevelOptionRead,
    SubjectOptionRead,
)
from .assignment_schema import (
    AssignmentCourseGroupRead,
    AssignmentCourseOptionRead,
    AssignmentCreate,
    AssignmentSubjectOptionRead,
    AssignmentSubjectRead,
    AssignmentTeacherRead,
    AssignmentUpdate,
    PaginatedAssignmentTeacher,
    TeacherAssignmentCourseRead,
    TeacherAssignmentCourseGroupRead,
    TeacherAssignmentSubjectRead,
    TeacherAssignmentsRead,
)
from .subject_schema import PaginatedSubject, SubjectCreate, SubjectRead, SubjectUpdate
from .term_schema import (
    EvaluationWeightLevelRead,
    EvaluationWeightRead,
    EvaluationWeightUpsert,
    TermCreate,
    TermRead,
    TermUpdate,
)

__all__ = [
    "SubjectCreate",
    "SubjectUpdate",
    "SubjectRead",
    "PaginatedSubject",
    "CourseCreate",
    "CourseUpdate",
    "CourseRead",
    "PaginatedCourse",
    "SchoolLevelOptionRead",
    "SubjectOptionRead",
    "CourseFormOptionsRead",
    "TermCreate",
    "TermUpdate",
    "TermRead",
    "EvaluationWeightUpsert",
    "EvaluationWeightRead",
    "EvaluationWeightLevelRead",
    "AssignmentTeacherRead",
    "PaginatedAssignmentTeacher",
    "AssignmentCourseOptionRead",
    "AssignmentSubjectOptionRead",
    "AssignmentCreate",
    "AssignmentUpdate",
    "AssignmentSubjectRead",
    "AssignmentCourseGroupRead",
    "TeacherAssignmentsRead",
    "TeacherAssignmentCourseRead",
    "TeacherAssignmentCourseGroupRead",
    "TeacherAssignmentSubjectRead",
]
